# Generated by Django 3.2.9 on 2021-12-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=150)),
                ('LastName', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('content', models.CharField(max_length=10000000)),
            ],
        ),
    ]
