# Generated by Django 3.2.9 on 2021-12-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=15000)),
                ('LastName', models.CharField(max_length=1500)),
                ('address', models.CharField(max_length=150000)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=15000)),
                ('birthplace', models.CharField(max_length=15000)),
                ('maritalstatus', models.CharField(max_length=1500)),
                ('interestinggame', models.CharField(max_length=1500)),
                ('interestingcountry', models.CharField(max_length=15000)),
            ],
        ),
    ]
